In [1]:
import torch

rand的范围是0 - 1

In [ ]:
torch.rand(3, 3)  

randn 的范围是 (-1) - 1

In [8]:
torch.randn(3, 3)

tensor([[ 1.8162,  2.4478, -0.1310],
        [ 1.3620,  0.1896,  1.4889],
        [-0.1614,  0.5273, -0.1996]])

自定义均值与方差 mean 均值  std : 方差

In [9]:
torch.normal(mean=torch.full([10], 0), std=torch.arange(1, 0, -0.1))

tensor([ 1.6912,  0.2930, -0.3318, -0.7835, -1.0363, -0.3957,  0.6152,  0.4504,
        -0.1066,  0.0051])

生成全是 7  的

In [11]:
torch.full([2, 3], 7)

tensor([[7., 7., 7.],
        [7., 7., 7.]])

arange函数

In [14]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

linspace

In [15]:
torch.linspace(0, 10 ,4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

生成0 - -1 再 * 10

In [16]:
torch.logspace(0, -1 , 10)

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [18]:
a = torch.zeros(3, 3)
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

随机不同的数(0-N)

In [19]:
torch.randperm(10)

tensor([6, 9, 3, 0, 1, 7, 2, 8, 4, 5])