reshape与view函数

In [13]:
import torch

view时要保证他们的size一样

In [14]:
a = torch.rand(4, 1 , 28, 28)
a.view(4, 28 * 28)

tensor([[0.3957, 0.1510, 0.4709,  ..., 0.1305, 0.2381, 0.2416],
        [0.9244, 0.3580, 0.4094,  ..., 0.7212, 0.8934, 0.8122],
        [0.8310, 0.5232, 0.5356,  ..., 0.5204, 0.2939, 0.4715],
        [0.0791, 0.3761, 0.6513,  ..., 0.0997, 0.4843, 0.8808]])

但是 view会破坏数据 上式 b.view(4, 28 ,28, 1) != a

squeeze&unsqueeze

In [15]:
a.view(4, 1, 28, 28)
a.unsqueeze(0).shape # 加维度

torch.Size([1, 4, 1, 28, 28])

利用squeeze维度的理解

In [16]:
a = torch.tensor([1.2, 2.3])
a.unsqueeze(-1)

tensor([[1.2000],
        [2.3000]])

In [17]:
a.unsqueeze(0)

tensor([[1.2000, 2.3000]])

维度扩展 expand(推荐)与repeat

In [21]:
b = torch.randn(1, 32, 1, 1)
b.expand(4, 32, 14, 14).shape

torch.Size([4, 32, 14, 14])

In [23]:
b = torch.randn(1, 32, 1, 1)
b.expand(-1, 32, -1, 4).shape

torch.Size([1, 32, 1, 4])

repeat 乘法

In [24]:
b.repeat(4, 1 , 1, 1).shape  

torch.Size([4, 32, 1, 1])

矩阵变换

In [26]:
a = torch.randn(2,3)
a.t().shape # 转置

torch.Size([3, 2])

In [27]:
#  transpose()
a = torch.randn(4, 3, 32, 32)
a.transpose(1, 3) # 交换1.3

# 怎么变回去呢?
a2 = a.transpose(1,3).contiguous().view(4, 3*32*32).view(4, 32, 32,3).transpose(1, 3)
torch.all(torch.eq(a, a2))

tensor(True)

In [28]:
# permute()
a = torch.rand(4, 3 , 28, 28)
a.permute(0, 2, 3, 1).shape

torch.Size([4, 28, 28, 3])