In [1]:
import torch

加减乘除

In [17]:
a = torch.rand(4, 784)
x = torch.rand(4, 784)
w = torch.rand(512, 784)
(x @ w.t()).shape

torch.Size([4, 512])

高维@ 只计算后两维

In [18]:
a = torch.rand(4, 3, 28, 64)
b = torch.rand(4, 1, 64, 32)
(a@b).shape

torch.Size([4, 3, 28, 32])

高次方

In [19]:
a = torch.full([2, 2], 3)
a.pow(2)

tensor([[9., 9.],
        [9., 9.]])

In [20]:
c = a.pow(2)
c.sqrt()

tensor([[3., 3.],
        [3., 3.]])

In [21]:
a = torch.exp(torch.ones(2, 2))
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [22]:
torch.log(a)

tensor([[1., 1.],
        [1., 1.]])

非重点

floor() : 向下取整 

ceil()  : 向上取整

trunc() : 提出整数部分

frac()  : 提出小数部分

round() : 四舍五入

重点: 

clamp : 梯度裁剪

In [23]:
grad = torch.rand(2, 3)*15
grad.median()

tensor(3.8620)

In [24]:
grad.clamp(8)

tensor([[ 8.0000,  8.0000, 14.3555],
        [ 9.1436,  8.0000,  8.0000]])