In [26]:
import torch

norm 范数

In [27]:
a = torch.full([8], 1)
b = a.view(2, 4)
c = a.view(2, 2, 2)

In [28]:
a.norm(2), b.norm(2), c.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

In [29]:
b.norm(2, dim=0) # 取指定维度范数

tensor([1.4142, 1.4142, 1.4142, 1.4142])

In [30]:
a = torch.arange(8).view(2, 4).float()
a.argmax() 
# 系统会将tensor打平为一维 ,然后取位置
# 如果不想打平, 那就要指定维度

tensor(7)

In [31]:
a = torch.randn(4, 10)
a.argmax(dim=1)

tensor([4, 3, 6, 8])

In [32]:
print(a.max(dim=1))
print('==================================================')
print(a.max(dim=1, keepdim=True))

torch.return_types.max(
values=tensor([1.3387, 1.0495, 0.6503, 0.9567]),
indices=tensor([4, 3, 6, 8]))
torch.return_types.max(
values=tensor([[1.3387],
        [1.0495],
        [0.6503],
        [0.9567]]),
indices=tensor([[4],
        [3],
        [6],
        [8]]))


取最大的几个 tpok()  

In [33]:
a.topk(3, dim=1)

torch.return_types.topk(
values=tensor([[ 1.3387,  1.1654,  1.0707],
        [ 1.0495,  0.9034,  0.5963],
        [ 0.6503,  0.0135, -0.0217],
        [ 0.9567,  0.8091,  0.7871]]),
indices=tensor([[4, 6, 1],
        [3, 4, 5],
        [6, 0, 9],
        [8, 4, 9]]))

In [37]:
a.topk(3, dim=1, largest=False)

torch.return_types.topk(
values=tensor([[-1.2203, -0.7162, -0.5197],
        [-0.4809, -0.2894, -0.2065],
        [-1.8291, -1.1733, -1.0755],
        [-0.4766, -0.3301, -0.0359]]),
indices=tensor([[0, 8, 5],
        [7, 1, 0],
        [2, 1, 5],
        [7, 1, 6]]))

kthvalue() : 第K小的值 及其索引

In [39]:
a.kthvalue(8, dim=1)

torch.return_types.kthvalue(
values=tensor([ 1.0707,  0.5963, -0.0217,  0.7871]),
indices=tensor([1, 5, 9, 9]))

比较 

In [40]:
a>0

tensor([[False,  True,  True,  True,  True, False,  True, False, False, False],
        [False, False, False,  True,  True,  True,  True, False, False,  True],
        [ True, False, False, False, False, False,  True, False, False, False],
        [ True, False,  True,  True,  True,  True, False, False,  True,  True]])

In [41]:
torch.eq(a, a) # 判断是否完全相等

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])